### ISSUE TITLE
Fails without error? Or "Illegal instruction (core dumped)"

### ISSUE THREAD

**Issue by privefl** [Yves-CHEN/DENTIST#2]
I'm trying DENTIST. It runs in 0.2 sec and provides no output file. 
I guess I run into some problem, but don't really get any error message.
Any idea what is going on?

This is the first lines of my sumstats file:
![sumstats](https://user-images.githubusercontent.com/11161036/87400847-a66cef00-c5b9-11ea-9369-113786524610.PNG)

**Comment by privefl** [comment]
In fact, I get one error message: `Illegal instruction (core dumped)`.

**Comment by privefl** [comment]
I tried using more recent nodes on my cluster. It now runs.
Are you using special instructions such as AVX2 instructions? On some older nodes, I cannot use PLINK2 with AVX2 instructions; it might be a similar issue here.

**Comment by Yves-CHEN** [comment]
The code uses an INTEL library MKL so that an executable is optimized for the instructions provided by the specific made of CPU. The static-compiled DENTIST is based on Intel(R) Xeon(R) CPU E5-2680 v3, which supports AVX2.

Thanks for reporting. This is a good point. I should note the computing infrastructure needed to run DENTIST.
