### ISSUE TITLE
[error] LD was set to 0

### ISSUE THREAD

**Issue by privefl** [Yves-CHEN/DENTIST#5]
For some chromosomes, I get the following error:

![dentist_error](https://user-images.githubusercontent.com/11161036/87412475-6150b900-c5c9-11ea-9a46-53e66c47d560.PNG)

Any idea where it comes from?

**Comment by Yves-CHEN** [comment]
Hi. This happens when the reference has NA genotypes. If this is the case for you, please add --with-NA-geno flag when running DENTIST, which should fix this.
Also please note that for good QC performance, a reference sample should be >5000 in sample size, and conventional QC are applied (e.g. HWE, MAC>5).

**Comment by privefl** [comment]
I don't seem to have this issue anymore with the new version.
But I don't think I had any missing values in the genotypes.
